# NAZWA STEROWNIKA
esphome:
  name: sm-lite-1616r
  friendly_name: sm-lite-1616r
  on_boot:
    then:
      # read the RTC time once when the system boots
      ds1307.read_time:

# KLUCZ HA - USTAW SWÓJ
api:
  encryption:
    key: !secret api_pass
  reboot_timeout: 0s

# KLUCZ OTA - USTAW SWÓJ
ota:
  - platform: esphome
    password: !secret ota_pass
# RODZAJ PROCESORA
esp32:
  board: esp32dev
  framework:
    type: arduino

# LOGOWANIE
logger:
  level: NONE
  logs:
    mqtt: NONE
    json: NONE
    uart: NONE

# KOMNUNIKACJA UART-RS485 - USTAW SWOJĄ CZESTOLIWOŚĆ
uart:
  rx_pin: 13
  tx_pin: 33
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8
  id: rs485_uart
  parity: NONE

# KONFIGURACJA CZUJNIKÓW I PERYFERIÓW
sensor:
  - platform: dallas_temp
#  address: 0x1234567812345628
    name: temperature
    update_interval: 120s
  # TEMPERATURA PROCESORA
  - platform: internal_temperature
    name: "Temperatura CPU"
    update_interval: 30s

  # CZUJNIK POMIARU TEMPERATURY PCB 1 - USTAW KTÓRE OBWODY MAJĄ BYĆ WYŁĄCZONE W PRZYPADKU PRZEKROCZENIA TEMPERATURY
  - platform: tmp102
    name: "Temperatura PCB 1"
    address: 0x48
    id: temp_1
    update_interval: 15s
    on_value_range:
        - above: 72.0
          then:
            
            - switch.turn_off: relay_02
            - switch.turn_off: relay_03
            - switch.turn_off: relay_04
            - switch.turn_off: relay_05
            - switch.turn_off: relay_06
            - switch.turn_off: relay_07
            - switch.turn_off: relay_08
            - switch.turn_off: relay_09
            - switch.turn_off: relay_10
            - switch.turn_off: relay_11
            - switch.turn_off: relay_12
            - switch.turn_off: relay_13
            - switch.turn_off: relay_14
            - switch.turn_off: relay_15
            - switch.turn_off: relay_16
            - switch.turn_on: alarm_01
        - below: 70.0
          then:
            - switch.turn_off: alarm_01
  - platform: dallas_temp
    #address: 0x1234567812345628
    name: temperature
    update_interval: 120s
  # CZUJNIK POMIARU TEMPERATURY PCB 1 - USTAW KTÓRE OBWODY MAJĄ BYĆ WYŁĄCZONE W PRZYPADKU PRZEKROCZENIA TEMPERATURY
  - platform: tmp102
    name: "Temperatura PCB 2"
    address: 0x49
    id: temp_2
    update_interval: 15s
    on_value_range:
        - above: 72.0
          then:
            
            - switch.turn_off: relay_02
            - switch.turn_off: relay_03
            - switch.turn_off: relay_04
            - switch.turn_off: relay_05
            - switch.turn_off: relay_06
            - switch.turn_off: relay_07
            - switch.turn_off: relay_08
            - switch.turn_off: relay_09
            - switch.turn_off: relay_10
            - switch.turn_off: relay_11
            - switch.turn_off: relay_12
            - switch.turn_off: relay_13
            - switch.turn_off: relay_14
            - switch.turn_off: relay_15
            - switch.turn_off: relay_16
            - switch.turn_on: alarm_01
        - below: 70.0
          then:
            - switch.turn_off: alarm_01

  # POMIAR CZASU OD OSTATNIEGO URUCHOMIENIA
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor_M03
    internal: true
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human_M03
            state: !lambda |-
              int seconds = round(id(uptime_sensor_M03).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  # POMIAR CZASU OD OSTATNIEGO URUCHOMIENIA
  - platform: uptime
    name: "Uptime Sensor M03"
    id: upt_M03
    internal: true

# KOFNIFGURACJA 1WIRE
one_wire:
  - platform: gpio
    pin: GPIO32

#KONFIGRUACJA ZEGARA CZASU RZECZYWISTEGO
time:
  - platform: ds1307
    id: ds1307_time
  - platform: sntp
    id: homeassistant_time
  - platform: sntp
    id: sntp_time
    timezone: Europe/Sofia
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:

# KONFIGURACJA LAN LUB WIFI
#ifi:
  #ssid: "12345678"
  #password: "12345678"
  #id: eth

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  power_pin: GPIO16
  clk_mode: GPIO17_OUT
  phy_addr: 1
  id: eth

  # STAŁE IP
  #manual_ip:
  #  static_ip: 192.168.68.89
  #  gateway: 192.168.68.1
  #  subnet: 255.255.255.0
  #  dns1 : 8.8.8.8
  #  dns2 : 8.8.4.4


# KONFIGURACJA I2C
i2c:
   - id: bus_a
     sda: 5
     scl: 15
     scan: true
     frequency: 400kHz

# KONFIGURACJA MCP23017
mcp23017:
  - id: 'mcp23017_hub_2'
    address: 0x21
  - id: 'mcp23017_hub_1'
    address: 0x20

button:
  - platform: restart
    name: "ESP Restart"
# KONFIGURACJA DIODY LED ORAZ BUZZERA OD ALARMU
light:
  - platform: binary
    output: relay_01
    name: "lampa 1"
    id: light01

output:
  - platform: gpio
    id: relay_01
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 8
      mode: OUTPUT
      inverted: false

switch:
  - platform: gpio
    pin: GPIO4
    name: "ALARM"
    id: alarm_01
  - platform: gpio
    pin: GPIO12
    name: "STATUS LED"
    id: status_01

#KONFIGURACJA WYJŚĆ

  - platform: gpio
    name: "REALY-02"
    id: relay_02
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 9
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-03"
    id: relay_03
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 10
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-04"
    id: relay_04
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 11
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-05"
    id: relay_05
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 12
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-06"
    id: relay_06
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 13
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-07"
    id: relay_07
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 14
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-08"
    id: relay_08
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 15
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-09"
    id: relay_09
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 0
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-10"
    id: relay_10
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 1
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-11"
    id: relay_11
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 2
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-12"
    id: relay_12
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 3
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-13"
    id: relay_13
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 4
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-14"
    id: relay_14
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 5
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-15"
    id: relay_15
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 6
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "REALY-16"
    id: relay_16
    pin:
      mcp23xxx: mcp23017_hub_1
      number: 7
      mode: OUTPUT
      inverted: false



# KONFIGURACJA WEJŚĆ
binary_sensor:

  - platform: gpio
    name: "INPUT-01"
    id: input_01
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 7
      mode:
        input: true
        pullup: false
      inverted: true
  - platform: gpio
    name: "INPUT-02"
    id: input_02
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 6
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-03"
    id: input_03
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 5
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-04"
    id: input_04
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 4
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-05"
    id: input_05
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 3
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-06"
    id: input_06
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 2
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-07"
    id: input_07
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 1
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-08"
    id: input_08
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 0
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-09"
    id: input_09
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 15
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-10"
    id: input_10
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 14
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-11"
    id: input_11
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 13
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-12"
    id: input_12
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 12
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-13"
    id: input_13
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 11
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-14"
    id: input_14
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 10
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-15"
    id: input_15
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 9
      mode:
        input: true
        pullup: false
      inverted: true

  - platform: gpio
    name: "INPUT-16"
    id: input_16
    pin:
      mcp23xxx: mcp23017_hub_2
      number: 8
      mode:
        input: true
        pullup: false
      inverted: true




# AKTYWACJA WEB SERWERA
web_server:
  port: 80

# USTAWIENIA ELEMENTÓW TEKSTOWYCH
text_sensor:
  - platform: template
    name: "ESP32-M03 Uptime"
    id: uptime_human_M03
    icon: mdi:clock-start
  - platform: template
    name: "IP"
    id: ip_address
    entity_category: diagnostic
    icon: "mdi:ip-network"
    lambda: return { id(eth).get_ip_addresses()[0].str() };
    update_interval: 10s

#USTAWENIA CZCIONEK
font:
- file: 'arial.ttf'
  id: font1
  size: 12

- file: 'materialdesignicons-webfont.ttf'
  id: materialdesignicons
  size: 15
  glyphs: [
      "\U000F0317", # lan
      "\U000F04A2", # signal
      "\U000F05A9", # wifi
      "\U000F048B", # server
      "\U000F0FA9", # clock
      "\U000F050F" # thermometer
      ]

# USTAWIENIA EKRANU
display:
  - platform: ssd1306_i2c
    model: "SSD1306_128X64"
    lambda: |-
      int seconds = round(id(upt_M03).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      it.print(0, 0, id(materialdesignicons), TextAlign::LEFT, "\U000F0317");
      it.printf(18, 1,id(font1), "%s", id(ip_address).state.c_str());
      it.print(0, 16, id(materialdesignicons), TextAlign::LEFT, "\U000F0FA9");
      it.printf(18,17,id(font1),"%d dni, %02d godzin",days,hours);
      it.print(0, 32, id(materialdesignicons), TextAlign::LEFT, "\U000F048B");
      it.printf(18, 33, id(font1), "SM-LITE-1616R");
      it.print(0, 48, id(materialdesignicons), TextAlign::LEFT, "\U000F050F");
      it.printf(18, 49, id(font1), "%.1f°, %.1f°", id(temp_1).state, id(temp_2).state);